version: '3.8'

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../api:/app
    networks:
      - reserving-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - reserving-network

networks:
  reserving-network:
    driver: bridge
